In [1]:
import numpy as np
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn import datasets
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

iris = datasets.load_iris()
data = iris.data[:, :2] #data
#print (data)
#print (label)
label = iris.target #label
clf = OneVsRestClassifier(SVC()).fit(data, label)
Y_Pred=clf.predict(data);
CM=confusion_matrix(label, Y_Pred)
print ("Confusion_Matrix = \n " ,CM)
print ("Confidence_Matrix = \n", CM/CM.max(axis=1))
print ("Accuarcy =" ,accuracy_score(label, Y_Pred))

#print (clf.get_params(deep=True))
#a = clf.score(data, label, clf.get_params(deep=True))



Confusion_Matrix = 
  [[50  0  0]
 [ 0 37 13]
 [ 0 15 35]]
Confidence_Matrix = 
 [[1.         0.         0.        ]
 [0.         1.         0.37142857]
 [0.         0.40540541 1.        ]]
Accuarcy = 0.8133333333333334
